
```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  fig.bg = "transparent",
  out.width = "100%"
)
```


# **Package Name**

---

## **Installation**

<!-- From CRAN (when published) -->
<!-- install.packages("SLAP") -->

```{r, results = "hide", warning = FALSE, message = FALSE}
# install.packages("devtools")      
install.packages("darkghastful/SLAP")
```

---

## **Quick Start**

### **Load the package**

```{r, results = "hide", warning = FALSE, message = FALSE}
library(package)
```

### **Usage example**

```{r, results = "hide", warning = FALSE, message = FALSE, eval=FALSE}

```

---

## **Functions**

### `function()`

Description

- **Arguments**  
  - `arg` — Arg description.
- **Returns**  
  - returns - Return description.
  
### **Example**
#### `function()`
Additional information.
```{r scale, fig.width=12, fig.asp=90/212, dpi=300, echo=FALSE}
function()
```

---

## **Dependencies**

- **bqutils**
- **stringr**  
- **jsonlite**
- **zip**  

---

## **License**

GPL-3.0 license © Bailey Quinn
